draw_ui() {
    clear
    echo -e "${C}┌──────────────────────────────────────────────────────────┐${N}"
    echo -e "${C}│${W}  ⚡  SWIFTMOD-A2Z : ANDROID MODDING TOOLKIT  ⚡        ${C}│${N}"
    echo -e "${C}└──────────────────────────────────────────────────────────┘${N}"
    echo -e "   ${G}Developer: SwiftMod-A2Z | Build: Stable-V1.0${N}"
    echo -e "${P}────────────────────────────────────────────────────────────${N}"
    echo -e "  ${G}1.  ⚡ Reboot to Bootloader (ADB)"
    echo -e "  ${G}2.  🔄 Reboot System (Fastboot)"
    echo -e "  ${G}3.  🛡️  Flash VBMETA (AVB Disable)"
    echo -e "  ${G}4.  🌀 Reboot to FastbootD (fastboot)"
    echo -e "  ${G}5.  📱 Flash GSI / System Image"
    echo -e "  ${G}6.  📦 Flash Super.img"
    echo -e "  ${G}7.  👞 Flash Boot.img"
    echo -e "  ${G}8.  🛠️  Flash Recovery.img"
    echo -e "  ${B}9.  🚀 Flash Init_Boot.img${N}"
    echo -e "  ${G}10. 🚀 Flash ROM via ADB Sideload (.zip)"
    echo -e "  ${C}11. 🔍 Check Fastboot Devices"
    echo -e "  ${C}12. 🔍 Check ADB Devices"
    echo -e "  ${G}13. 📂 Flash Fastboot ROM (script needed)"
    echo -e "  ${B}14. ⌨️  Manual Command Execution"
    echo -e "  ${R}15. 🧹 Format Data (Wipe All Data)"
    echo -e "  ${Y}16. 📜 View / Clear Flash Logs"
    echo -e "  ${R}17. 🔓 Unlock Bootloader (No Xiaomi)"
    echo -e "  ${C}18. 🔄 Switch Active Slot (A/B)${N}"
    echo -e "  ${R}0.  ❌ Exit Tool${N}"
    
    # --- Clean Aligned Input Section ---
    echo -e "\n${C}┌──────────────────────────────────────────────────────────┐${N}"
    echo -e "${C}│${N} ${W}Enter your choice [0-18] below:${N}                        ${C}│${N}"
    echo -e "${C}└──────────────────────────────────────────────────────────┘${N}"
}
